version: '3'
services:
  auth:
    container_name: auth-nodejs
    restart: always
    image: sarhan/auth-nodejs
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - public
      - private
    environment:
      - HOST=localhost
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/auth
      - PORT=5000
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./auth-volume/db:/data/db
    networks:
      - private
    ports:
      - "27017:27017"
networks:
  private:
    driver: bridge
  public:
    driver: bridge
